In [1]:
import tensorflow as tf
import numpy as np
from ops import *

In [2]:
sess = tf.InteractiveSession()

In [9]:
# ops.time_to_batch

value = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ]
])

print(value.shape)

x = time_to_batch(value, dilation=1)
y = time_to_batch(value, dilation=2)
z = time_to_batch(value, dilation=5)

x,y,z = sess.run([x, y, z])

print(np.array(x).shape)
print(x)
print(np.array(y).shape)
print(y)
print(np.array(z).shape)
print(z)

(1, 2, 3)
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
(2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]
(5, 1, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]]


In [8]:
# ops.batch_to_time

value = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ]
])

print(value.shape)

x = time_to_batch(value, dilation=1)
y = time_to_batch(value, dilation=2)
z = time_to_batch(value, dilation=5)

x = batch_to_time(x, dilation=1)
y = batch_to_time(y, dilation=2)
z = batch_to_time(z, dilation=5)

x,y,z = sess.run([x, y, z])

print(np.array(x).shape)
print(x)
print(np.array(y).shape)
print(y)
print(np.array(z).shape)
print(z)

(1, 2, 3)
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
(1, 5, 3)
[[[1 2 3]
  [4 5 6]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
