In [9]:
import tensorflow as tf
from tensorflow.python.framework import tensor_shape
from tensorflow.python.framework import ops
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import check_ops

from attention_wrapper import *

In [17]:
sess = tf.InteractiveSession()

In [4]:
'Ç'.lower()

'ç'

In [5]:
import re

text = "EG abcdefghijklmnopqrstuvwxyz'çéâêîôûàèùëïü"

re.sub(r"[^ a-zçéâêîôûàèùëïü]", "", text.strip().lower())

'eg abcdefghijklmnopqrstuvwxyzçéâêîôûàèùëïü'

In [19]:
# concat

ns = concat(prefix=3, suffix=7, static=False)

s = concat(prefix=3, suffix=7, static=True)

shape1 = tensor_shape.TensorShape([3, 7])
shape2 = tensor_shape.TensorShape([2, 5])

print(ns)
print(sess.run(ns))
print(s)
print(concat(shape1, shape2, True))


Tensor("concat_12:0", shape=(2,), dtype=int32)
[3 7]
[3, 7]
[3, 7, 2, 5]


In [22]:
# zero_state_tensors

zst = zero_state_tensors(state_size=10, batch_size=32, dtype=tf.int32)

print(zst.shape)

print(sess.run(zst))

(32, 10)
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [23]:
t1 = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
])

t2 = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
])

t3 = t1 + t2
print(t3.shape)

sess.run(t3)

(1, 4, 3)


array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]]], dtype=int32)