In [35]:
import tensorflow as tf
from tensorflow.python.framework import tensor_shape
from tensorflow.python.framework import ops
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import check_ops
from tensorflow.python.util import nest

from attention_wrapper import *

In [17]:
sess = tf.InteractiveSession()

In [4]:
'Ç'.lower()

'ç'

In [5]:
import re

text = "EG abcdefghijklmnopqrstuvwxyz'çéâêîôûàèùëïü"

re.sub(r"[^ a-zçéâêîôûàèùëïü]", "", text.strip().lower())

'eg abcdefghijklmnopqrstuvwxyzçéâêîôûàèùëïü'

In [19]:
# concat

ns = concat(prefix=3, suffix=7, static=False)

s = concat(prefix=3, suffix=7, static=True)

shape1 = tensor_shape.TensorShape([3, 7])
shape2 = tensor_shape.TensorShape([2, 5])

print(ns)
print(sess.run(ns))
print(s)
print(concat(shape1, shape2, True))


Tensor("concat_12:0", shape=(2,), dtype=int32)
[3 7]
[3, 7]
[3, 7, 2, 5]


In [22]:
# zero_state_tensors

zst = zero_state_tensors(state_size=10, batch_size=32, dtype=tf.int32)

print(zst.shape)

print(sess.run(zst))

(32, 10)
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [23]:
t1 = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
])

t2 = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
])

t3 = t1 + t2
print(t3.shape)

sess.run(t3)

(1, 4, 3)


array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]]], dtype=int32)

In [29]:
t1 = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
])

t2 = tf.constant([
    [
        [11,12,13],
        [14,15,16],
        [17,18,19],
        [110,111,112]
    ]
])

c1 = array_ops.concat([t1, t2], axis=-1)

c2 = array_ops.concat([t1, t2], axis=2)

print(sess.run(c1))
print(sess.run(c2))

[[[  1   2   3  11  12  13]
  [  4   5   6  14  15  16]
  [  7   8   9  17  18  19]
  [ 10  11  12 110 111 112]]]
[[[  1   2   3  11  12  13]
  [  4   5   6  14  15  16]
  [  7   8   9  17  18  19]
  [ 10  11  12 110 111 112]]]


In [34]:
# array_ops.identity

t = tf.constant([1,2,3,4,5,6,7])

t2 = array_ops.identity(t)

sess.run(t2)

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [37]:
#  nest.map_structure

t = tf.constant([1,2,3,4,5,6,7])

f = lambda v: v*2

t2 = nest.map_structure(f, t)

sess.run(t2)

array([ 2,  4,  6,  8, 10, 12, 14], dtype=int32)

In [42]:
# ops.control_dependencies

t1 = tf.constant([1,2,3])
t2 = tf.constant([4,5,6])

with ops.control_dependencies(
    [check_ops.assert_equal(t1, t1, message="Not equal.")]):
    print("equal")

with ops.control_dependencies(
    [check_ops.assert_equal(t1, t2, message="Not equal.")]):
    print("equal")

equal


ValueError: Not equal.
Condition x == y did not hold element-wise:
x (Const_106:0) = 
[1 2 3]
y (Const_107:0) = 
[4 5 6]

In [48]:
# array_ops.squeeze

help(array_ops.squeeze)

t = tf.constant([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])

print(t.shape)

t2 = array_ops.squeeze(t, axis=[1])

print(t2.shape)

print(sess.run(t2))

Help on function squeeze in module tensorflow.python.ops.array_ops:

squeeze(input, axis=None, name=None, squeeze_dims=None)
    Removes dimensions of size 1 from the shape of a tensor.
    
    Given a tensor `input`, this operation returns a tensor of the same type with
    all dimensions of size 1 removed. If you don't want to remove all size 1
    dimensions, you can remove specific size 1 dimensions by specifying
    `axis`.
    
    For example:
    
    ```prettyprint
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    shape(squeeze(t)) ==> [2, 3]
    ```
    
    Or, to remove specific size 1 dimensions:
    
    ```prettyprint
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    shape(squeeze(t, [2, 4])) ==> [1, 2, 3, 1]
    ```
    
    Args:
      input: A `Tensor`. The `input` to squeeze.
      axis: An optional list of `ints`. Defaults to `[]`.
        If specified, only squeezes the dimensions listed. The dimension
        index starts at 0. It is an error to squeeze a