In [1]:
import tensorflow as tf
import numpy as np

In [4]:
sess = tf.InteractiveSession()

In [5]:
t = tf.constant([
    [
        [0,1,2],
        [3,4,5],
        [6,7,8],
        [9,10,11],
        [12,13,14]
    ]
])

print(t.shape)

help(tf.transpose)

tt = tf.transpose(t, perm=[1,0,2])

print(tt.shape)

sess.run(tt)

(1, 5, 3)
Help on function transpose in module tensorflow.python.ops.array_ops:

transpose(a, perm=None, name='transpose')
    Transposes `a`. Permutes the dimensions according to `perm`.
    
    The returned tensor's dimension i will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is
    the rank of the input tensor. Hence by default, this operation performs a
    regular matrix transpose on 2-D input Tensors.
    
    For example:
    
    ```python
    # 'x' is [[1 2 3]
    #         [4 5 6]]
    tf.transpose(x) ==> [[1 4]
                         [2 5]
                         [3 6]]
    
    # Equivalently
    tf.transpose(x, perm=[1, 0]) ==> [[1 4]
                                      [2 5]
                                      [3 6]]
    
    # 'perm' is more useful for n-dimensional tensors, for n > 2
    # 'x' is   [[[1  2  3]
    #            [4  5  6]]
    #           [[7  8  9]
    #            [10 11 12]]]
    # Ta

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]], dtype=int32)