In [1]:
import tensorflow as tf
import numpy as np
from hyperparams import Hyperparams as hp

In [4]:
tf.__version__

'1.2.0'

In [11]:
#  tf.concat in embed

n = 10
lookup_table = tf.placeholder(tf.int32, name = 'lookup_table')
pad = tf.zeros(shape=[1, n], dtype=tf.int32)
g = tf.concat([pad, lookup_table[1:, :]], axis=0)

lt = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

with tf.Session() as sess:
    a = sess.run(g, feed_dict={lookup_table: lt})
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], dtype=int32)

In [18]:
# tf.nn.embedding_lookup in embed

help(tf.nn.embedding_lookup)

vocabulary_size = 10
embedding_dimension = 3

lookup_table = tf.constant(np.random.normal(size=[vocabulary_size, embedding_dimension]))
inputs = tf.placeholder(tf.int32, name='inputs')

g = tf.nn.embedding_lookup(lookup_table, inputs)

input_value = [9,8,7,6,5,4,3,2,1,0]

with tf.Session() as sess:
        lt = sess.run(lookup_table)
        a = sess.run(g, feed_dict={inputs: input_value})
print('lookup_table = {}'.format(lt))
print('looked up embeddings = {}'.format(a))

Help on function embedding_lookup in module tensorflow.python.ops.embedding_ops:

embedding_lookup(params, ids, partition_strategy='mod', name=None, validate_indices=True, max_norm=None)
    Looks up `ids` in a list of embedding tensors.
    
    This function is used to perform parallel lookups on the list of
    tensors in `params`.  It is a generalization of
    [`tf.gather()`](../../api_docs/python/array_ops.md#gather), where `params` is
    interpreted as a partitioning of a large embedding tensor.  `params` may be
    a `PartitionedVariable` as returned by using `tf.get_variable()` with a
    partitioner.
    
    If `len(params) > 1`, each element `id` of `ids` is partitioned between
    the elements of `params` according to the `partition_strategy`.
    In all strategies, if the id space does not evenly divide the number of
    partitions, each of the first `(max_id + 1) % len(params)` partitions will
    be assigned one more id.
    
    If `partition_strategy` is `"mod"`, we 

In [20]:
# tf.contrib.layers.batch_norm

# related operation
# tf.nn.batch_normalization

help(tf.contrib.layers.batch_norm)

Help on function batch_norm in module tensorflow.contrib.layers.python.layers.layers:

batch_norm(inputs, decay=0.999, center=True, scale=False, epsilon=0.001, activation_fn=None, param_initializers=None, updates_collections='update_ops', is_training=True, reuse=None, variables_collections=None, outputs_collections=None, trainable=True, batch_weights=None, fused=False, data_format='NHWC', zero_debias_moving_mean=False, scope=None)
    Adds a Batch Normalization layer from http://arxiv.org/abs/1502.03167.
    
      "Batch Normalization: Accelerating Deep Network Training by Reducing
      Internal Covariate Shift"
    
      Sergey Ioffe, Christian Szegedy
    
    Can be used as a normalizer function for conv2d and fully_connected.
    
    Note: When is_training is True the moving_mean and moving_variance need to be
    updated, by default the update_ops are placed in `tf.GraphKeys.UPDATE_OPS` so
    they need to be added as a dependency to the `train_op`, example:
    
      update_

In [23]:
# tf.contrib.layers.layer_norm

help(tf.contrib.layers.layer_norm)

Help on function layer_norm in module tensorflow.contrib.layers.python.layers.layers:

layer_norm(inputs, center=True, scale=True, activation_fn=None, reuse=None, variables_collections=None, outputs_collections=None, trainable=True, scope=None)
    Adds a Layer Normalization layer from https://arxiv.org/abs/1607.06450.
    
      "Layer Normalization"
    
      Jimmy Lei Ba, Jamie Ryan Kiros, Geoffrey E. Hinton
    
    Can be used as a normalizer function for conv2d and fully_connected.
    
    Args:
      inputs: a tensor with 2 or more dimensions. The normalization
              occurs over all but the first dimension.
      center: If True, add offset of `beta` to normalized tensor. If False, `beta`
        is ignored.
      scale: If True, multiply by `gamma`. If False, `gamma` is
        not used. When the next layer is linear (also e.g. `nn.relu`), this can be
        disabled since the scaling can be done by the next layer.
      activation_fn: activation function, default se

In [30]:
g = tf.constant([[0,1], [1,2], [2,3]])

g.get_shape().as_list()

[3, 2]

In [32]:
# tf.pad

help(tf.pad)

pad_len = 5

inputs = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15]
    ]
])

g = tf.pad(inputs, [[0,0], [pad_len, 0], [0,0]])

with tf.Session() as sess:
    a = sess.run(g)
a

Help on function pad in module tensorflow.python.ops.array_ops:

pad(tensor, paddings, mode='CONSTANT', name=None)
    Pads a tensor.
    
    This operation pads a `tensor` according to the `paddings` you specify.
    `paddings` is an integer tensor with shape `[n, 2]`, where n is the rank of
    `tensor`. For each dimension D of `input`, `paddings[D, 0]` indicates how
    many values to add before the contents of `tensor` in that dimension, and
    `paddings[D, 1]` indicates how many values to add after the contents of
    `tensor` in that dimension. If `mode` is "REFLECT" then both `paddings[D, 0]`
    and `paddings[D, 1]` must be no greater than `tensor.dim_size(D) - 1`. If
    `mode` is "SYMMETRIC" then both `paddings[D, 0]` and `paddings[D, 1]` must be
    no greater than `tensor.dim_size(D)`.
    
    The padded size of each dimension D of the output is:
    
    `paddings[D, 0] + tensor.dim_size(D) + paddings[D, 1]`
    
    For example:
    
    ```python
    # 't' is [[1, 2, 

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]], dtype=int32)

In [64]:
# tf.conv1d

help(tf.layers.conv1d)

inputs = tf.constant([
    [
    [1,2,3,0],
    [0,1,2,3],
    [3,0,1,2],
    [2,3,0,1]
    ]
], dtype=tf.float32)

filters = 1
kernel_size = 3

kernel_initializer = tf.constant_initializer(1.)

g = tf.layers.conv1d(inputs=inputs,
                     filters=filters,
                     kernel_size=kernel_size,
                     kernel_initializer=kernel_initializer,
                     use_bias=False)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    a = sess.run(g)
a

Help on function conv1d in module tensorflow.python.layers.convolutional:

conv1d(inputs, filters, kernel_size, strides=1, padding='valid', data_format='channels_last', dilation_rate=1, activation=None, use_bias=True, kernel_initializer=None, bias_initializer=<tensorflow.python.ops.init_ops.Zeros object at 0x114976748>, kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, trainable=True, name=None, reuse=None)
    Functional interface for 1D convolution layer (e.g. temporal convolution).
    
    This layer creates a convolution kernel that is convolved
    (actually cross-correlated) with the layer input to produce a tensor of
    outputs. If `use_bias` is True (and a `bias_initializer` is provided),
    a bias vector is created and added to the outputs. Finally, if
    `activation` is not `None`, it is applied to the outputs as well.
    
    Arguments:
      inputs: Tensor input.
      filters: integer, the dimensionality of the output space (i.e. the number
  

array([[[ 18.],
        [ 18.]]], dtype=float32)

In [3]:
# tf.contrib.seq2seq.BahdanauAttention

help(tf.contrib.seq2seq.BahdanauAttention)

Help on class BahdanauAttention in module tensorflow.contrib.seq2seq.python.ops.attention_wrapper:

class BahdanauAttention(_BaseAttentionMechanism)
 |  Implements Bhadanau-style (additive) attention.
 |  
 |  This attention has two forms.  The first is Bhandanau attention,
 |  as described in:
 |  
 |  Dzmitry Bahdanau, Kyunghyun Cho, Yoshua Bengio.
 |  "Neural Machine Translation by Jointly Learning to Align and Translate."
 |  ICLR 2015. https://arxiv.org/abs/1409.0473
 |  
 |  The second is the normalized form.  This form is inspired by the
 |  weight normalization article:
 |  
 |  Tim Salimans, Diederik P. Kingma.
 |  "Weight Normalization: A Simple Reparameterization to Accelerate
 |   Training of Deep Neural Networks."
 |  https://arxiv.org/abs/1602.07868
 |  
 |  To enable the second form, construct the object with parameter
 |  `normalize=True`.
 |  
 |  Method resolution order:
 |      BahdanauAttention
 |      _BaseAttentionMechanism
 |      AttentionMechanism
 |      built

In [3]:
# tf.contrib.seq2seq.AttentionWrapper

help(tf.contrib.seq2seq.AttentionWrapper)

Help on class AttentionWrapper in module tensorflow.contrib.seq2seq.python.ops.attention_wrapper:

class AttentionWrapper(tensorflow.python.ops.rnn_cell_impl.RNNCell)
 |  Wraps another `RNNCell` with attention.
 |  
 |  Method resolution order:
 |      AttentionWrapper
 |      tensorflow.python.ops.rnn_cell_impl.RNNCell
 |      tensorflow.python.layers.base.Layer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, cell, attention_mechanism, attention_layer_size=None, alignment_history=False, cell_input_fn=None, output_attention=True, initial_cell_state=None, name=None)
 |      Construct the `AttentionWrapper`.
 |      
 |      Args:
 |        cell: An instance of `RNNCell`.
 |        attention_mechanism: An instance of `AttentionMechanism`.
 |        attention_layer_size: Python integer, the depth of the attention (output)
 |          layer. If None (default), use the context as attention at each time
 |          step. Otherwise, feed the context and cell out

In [18]:
# tf.layers.dense

help(tf.layers.dense)

inputs1 = tf.constant([[1,2], [3,4]])
inputs2 = tf.constant([[1,2], [3,4]])

g = tf.layers.dense(inputs1, units=1, activation=None, kernel_initializer=tf.constant_initializer([1,2]))
f = tf.layers.dense(inputs2, units=2, activation=None, kernel_initializer=tf.constant_initializer([[1,2], [1,2]]))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    gv= sess.run(g)
    fv = sess.run(f)

a = np.array([[1,2], [3,4]])
b = np.array([1,2])
gva = np.matmul(a, b)    

c = np.array([[1,2], [3,4]])
d = np.array([[1,2], [1,2]])
fva = np.matmul(c, d)
    
print(gv)
print(gva)
print()

print(fv)
print(fva)


Help on function dense in module tensorflow.python.layers.core:

dense(inputs, units, activation=None, use_bias=True, kernel_initializer=None, bias_initializer=<tensorflow.python.ops.init_ops.Zeros object at 0x118c940b8>, kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, trainable=True, name=None, reuse=None)
    Functional interface for the densely-connected layer.
    
    This layer implements the operation:
    `outputs = activation(inputs.kernel + bias)`
    Where `activation` is the activation function passed as the `activation`
    argument (if not `None`), `kernel` is a weights matrix created by the layer,
    and `bias` is a bias vector created by the layer
    (only if `use_bias` is `True`).
    
    Note: if the `inputs` tensor has a rank greater than 2, then it is
    flattened prior to the initial matrix multiply by `kernel`.
    
    Arguments:
      inputs: Tensor input.
      units: Integer or Long, dimensionality of the output space.
      acti

## ToDo:

- [ ] tf.layers.conv1d
- [ ] tf.contrib.rnn.GRUCell
- [ ] tf.nn.bidirectional_dynamic_rnn
- [ ] tf.nn.dynamic_rnn
- [ ] tf.contrib.seq2seq.BahdanauAttention
- [ ] tf.contrib.seq2seq.AttentionWrapper