In [1]:
import tensorflow as tf
from modules import *

In [2]:
sess = tf.InteractiveSession()

In [27]:
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19]
    ]
], dtype=tf.float32)

print(x.shape)

with tf.variable_scope("scope1") as scope:
    y1 = conv1d(x, filters=1, reuse=False)
with tf.variable_scope("scope2") as scope:
    y3 = conv1d(x, filters=3, reuse=False)
with tf.variable_scope("scope3") as scope:
    y9 = conv1d(x, filters=9, reuse=False)

print("y1.shape={}".format(y1.shape))
print("y3.shape={}".format(y3.shape))
print("y9.shape={}".format(y9.shape))

sess.run(tf.global_variables_initializer())
sess.run([y1, y3, y9])

(2, 2, 9)
y1.shape=(2, 2, 1)
y3.shape=(2, 2, 3)
y9.shape=(2, 2, 9)


[array([[[ 3.74701381],
         [-0.05998921]],
 
        [[ 3.4762814 ],
         [ 0.21074224]]], dtype=float32),
 array([[[  9.25084496,   7.88460159,  -0.51482272],
         [ 34.76470947,  22.31612396, -14.63024902]],
 
        [[ 22.46191216,  21.70064926, -11.59332371],
         [ 21.55364418,   8.50007725,  -3.55174589]]], dtype=float32),
 array([[[  4.06030607,  -5.42709064,  -4.03212547,   2.62543869,
            3.68844223,   2.34196329,   5.7512126 ,  -0.41432744,
            3.2863965 ],
         [ 10.65616226, -17.18771172, -15.0378952 ,   9.01805496,
           10.04689598,  -1.73798656,  13.41705704,   0.24387491,
           15.16287804]],
 
        [[  7.75498247, -20.37667465, -17.51118279,   4.15194798,
            2.1599865 ,  -2.47971344,  10.72668076,  -6.40786886,
           16.91406631],
         [  6.96148682,  -2.23812914,  -1.55883956,   7.49154615,
           11.57535172,   3.08368897,   8.44158936,   6.23741627,
            1.53520679]]], dtype=float32)]

In [30]:
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19],
        [21,22,23,24,25,26,27,28,29]
    ]
], dtype=tf.float32)

print(x.shape)

with tf.variable_scope("scope1c") as scope:
    y1 = conv1d(x, filters=9, size=1)
with tf.variable_scope("scope2c") as scope:
    y2 = conv1d(x, filters=9, size=2)
with tf.variable_scope("scope3c") as scope:
    y3 = conv1d(x, filters=9, size=3)

print("y1.shape={}".format(y1.shape))
print("y2.shape={}".format(y2.shape))
print("y3.shape={}".format(y3.shape))

sess.run(tf.global_variables_initializer())
sess.run([y1, y2, y3])

(4, 3, 9)
y1.shape=(4, 3, 9)
y2.shape=(4, 3, 9)
y3.shape=(4, 3, 9)


[array([[[ -3.05774593,  -2.26609755,   3.43342209,  -5.87648392,
           10.65005207,  -0.1943562 ,   4.47221518,   0.78416568,
          -11.31748486],
         [ -6.031991  , -11.05277824,  14.24045849,  -5.6730175 ,
           20.66442871,   6.50884962,  11.58832264,   7.52513456,
          -32.25483704],
         [ -9.00623703, -19.83946228,  25.0474968 ,  -5.46955204,
           30.67880821,  13.21205616,  18.70442963,  14.26610184,
          -53.19219589]],
 
        [[ -5.22357368,  -4.3438549 ,  16.17678452,   1.50319576,
           11.24172497,   8.57348442,   6.58650827,   5.97674513,
          -24.32057953],
         [ -3.86616349,  -8.97502136,   1.49709606, -13.05269814,
           20.07275581,  -2.25899172,   9.47402954,   2.33255529,
          -19.25174713],
         [ -9.00623703, -19.83946228,  25.0474968 ,  -5.46955204,
           30.67880821,  13.21205616,  18.70442963,  14.26610184,
          -53.19219589]],
 
        [[ -3.05774593,  -2.26609755,   3.43342209, 

In [7]:
# max pool

x = tf.constant([
     [
        [1,2,3],
        [11,12,13],
        [21,22,23],
        [41,42,43],
        [51,52,53],
        [61,62,63]
    ],
    [
        [71,72,73],
        [1,2,3],
        [81,82,83],
        [21,22,23],
        [91,92,93],
        [31,32,33],
    ]
])

print(x.shape)

ys1 = tf.layers.max_pooling1d(x, pool_size=2, strides=1, padding='same')

ys2 = tf.layers.max_pooling1d(x, pool_size=2, strides=2, padding='same')

yv1 = tf.layers.max_pooling1d(x, pool_size=2, strides=1, padding='valid')

yv2 = tf.layers.max_pooling1d(x, pool_size=2, strides=2, padding='valid')

print("ys1.shape = {}".format(ys1.shape))

print("ys2.shape = {}".format(ys2.shape))

print("yv1.shape = {}".format(yv1.shape))

print("yv2.shape = {}".format(yv2.shape))

ys1,  ys2, yv1, yv2 = sess.run([ys1,  ys2, yv1, yv2])

print(ys1)
print(ys2)
print(yv1)
print(yv2)

(2, 6, 3)
ys1.shape = (2, 6, 3)
ys2.shape = (2, 3, 3)
yv1.shape = (2, 5, 3)
yv2.shape = (2, 3, 3)
[[[11 12 13]
  [21 22 23]
  [41 42 43]
  [51 52 53]
  [61 62 63]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [81 82 83]
  [91 92 93]
  [91 92 93]
  [31 32 33]]]
[[[11 12 13]
  [41 42 43]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [91 92 93]]]
[[[11 12 13]
  [21 22 23]
  [41 42 43]
  [51 52 53]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [81 82 83]
  [91 92 93]
  [91 92 93]]]
[[[11 12 13]
  [41 42 43]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [91 92 93]]]


In [33]:
# residual connection with different shape
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19]
    ]
])

print(x.shape)

y = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9]
    ],
    [
        [11,2,13,14,5,16,7,18,9]
    ]
])

print(y.shape)

sess.run(x + y)

(2, 2, 9)
(2, 1, 9)


array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
        [12, 14, 16, 18, 20, 22, 24, 26, 28]],

       [[22,  4, 26, 28, 10, 32, 14, 36, 18],
        [12, 14, 16, 18, 20, 22, 24, 26, 28]]], dtype=int32)