In [1]:
import tensorflow as tf
import numpy as np
from modules import *

In [2]:
sess = tf.InteractiveSession()

In [26]:
from tensorflow.python.layers.convolutional import *

conv1d = Conv1D(filters=5, kernel_size=2, padding='same', kernel_initializer=tf.constant_initializer(1.0))

with tf.variable_scope("conv1d13") as scope:
    conv1d.build(input_shape=3)

print("conv1d.kernel.shape = {}".format(conv1d.kernel.shape))

inputs = tf.constant([
    [
        [2,3,5],
        [3,7,11],
        [5,7,2],
        [11,3,7],
        [2,2,5],
        [5,7,2],
        [11,3,5],
        [7,7,2],
        [5,11,3]
    ]
], dtype=tf.float32)

print("inputs.shape = {}".format(inputs.shape))

tensor = conv1d.call(inputs=inputs)

print("tensor.shape = {}".format(tensor.shape))

sess.run(tf.global_variables_initializer())
sess.run(tensor)

conv1d.kernel.shape = (2, 3, 5)
inputs.shape = (1, 9, 3)
tensor.shape = (1, 9, 5)


array([[[ 31.,  31.,  31.,  31.,  31.],
        [ 35.,  35.,  35.,  35.,  35.],
        [ 35.,  35.,  35.,  35.,  35.],
        [ 30.,  30.,  30.,  30.,  30.],
        [ 23.,  23.,  23.,  23.,  23.],
        [ 33.,  33.,  33.,  33.,  33.],
        [ 35.,  35.,  35.,  35.,  35.],
        [ 35.,  35.,  35.,  35.,  35.],
        [ 19.,  19.,  19.,  19.,  19.]]], dtype=float32)

In [40]:
# matrix convolution

kernel = np.array([
    [1,1,1,1,1],
    [1,1,1,1,1]
])

s0 = np.array([
    [2,3,5],
    [3,7,11]
])

filtered0 = np.matmul(kernel.T, s0)

print("filtered[0] = {}".format(filtered0))
print("conv[0] = {}".format(np.sum(filtered0, axis=1)))
      
s1 = np.array([
    [3,7,11],
    [5,7,2]
])

filtered1 = np.matmul(kernel.T, s1)

print("filtered[1] = {}".format(filtered1))
print("conv[1] = {}".format(np.sum(filtered1, axis=1)))

filtered[0] = [[ 5 10 16]
 [ 5 10 16]
 [ 5 10 16]
 [ 5 10 16]
 [ 5 10 16]]
conv[0] = [31 31 31 31 31]
filtered[1] = [[ 8 14 13]
 [ 8 14 13]
 [ 8 14 13]
 [ 8 14 13]
 [ 8 14 13]]
conv[1] = [35 35 35 35 35]


In [3]:
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19]
    ]
], dtype=tf.float32)

print(x.shape)

with tf.variable_scope("scope1") as scope:
    y1 = conv1d(x, filters=1, reuse=False)
with tf.variable_scope("scope2") as scope:
    y3 = conv1d(x, filters=3, reuse=False)
with tf.variable_scope("scope3") as scope:
    y9 = conv1d(x, filters=9, reuse=False)
    
print("y1.shape={}".format(y1.shape))
print("y3.shape={}".format(y3.shape))
print("y9.shape={}".format(y9.shape))

sess.run(tf.global_variables_initializer())
sess.run([y1, y3, y9])

(2, 2, 9)
y1.shape=(2, 2, 1)
y3.shape=(2, 2, 3)
y9.shape=(2, 2, 9)


[array([[[ 5.49275064],
         [ 6.29155207]],
 
        [[ 7.59192133],
         [ 4.19238043]]], dtype=float32),
 array([[[ -4.47373581,  16.6560421 ,  -6.19846821],
         [ -7.24971962,  40.17018509, -17.6416893 ]],
 
        [[ -6.95903969,  31.2115345 ,  -1.48884821],
         [ -4.76441479,  25.61469078, -22.35130692]]], dtype=float32),
 array([[[ -3.29325104,   2.26920414,   1.71366632,  -9.02971172,
           -3.24299312,   2.92663336,  -1.66209507, -12.26705933,
           -3.9431169 ],
         [  1.80036354,   4.87177753,   9.69713593, -21.70931625,
           -8.00884247,   3.37249517, -13.12925816, -33.5377121 ,
          -17.22974777]],
 
        [[  4.24589205,  12.31800652,  12.23772049, -12.31015587,
           -3.95720553,  -0.29997492, -15.08893585, -29.85498047,
          -22.79883766],
         [ -5.73877954,  -5.17702579,  -0.82691717, -18.42887497,
           -7.29463005,   6.59910345,   0.2975843 , -15.94978905,
            1.62597132]]], dtype=float32)]

In [30]:
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19],
        [21,22,23,24,25,26,27,28,29]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19],
        [21,22,23,24,25,26,27,28,29]
    ]
], dtype=tf.float32)

print(x.shape)

with tf.variable_scope("scope1c") as scope:
    y1 = conv1d(x, filters=9, size=1)
with tf.variable_scope("scope2c") as scope:
    y2 = conv1d(x, filters=9, size=2)
with tf.variable_scope("scope3c") as scope:
    y3 = conv1d(x, filters=9, size=3)

print("y1.shape={}".format(y1.shape))
print("y2.shape={}".format(y2.shape))
print("y3.shape={}".format(y3.shape))

sess.run(tf.global_variables_initializer())
sess.run([y1, y2, y3])

(4, 3, 9)
y1.shape=(4, 3, 9)
y2.shape=(4, 3, 9)
y3.shape=(4, 3, 9)


[array([[[ -3.05774593,  -2.26609755,   3.43342209,  -5.87648392,
           10.65005207,  -0.1943562 ,   4.47221518,   0.78416568,
          -11.31748486],
         [ -6.031991  , -11.05277824,  14.24045849,  -5.6730175 ,
           20.66442871,   6.50884962,  11.58832264,   7.52513456,
          -32.25483704],
         [ -9.00623703, -19.83946228,  25.0474968 ,  -5.46955204,
           30.67880821,  13.21205616,  18.70442963,  14.26610184,
          -53.19219589]],
 
        [[ -5.22357368,  -4.3438549 ,  16.17678452,   1.50319576,
           11.24172497,   8.57348442,   6.58650827,   5.97674513,
          -24.32057953],
         [ -3.86616349,  -8.97502136,   1.49709606, -13.05269814,
           20.07275581,  -2.25899172,   9.47402954,   2.33255529,
          -19.25174713],
         [ -9.00623703, -19.83946228,  25.0474968 ,  -5.46955204,
           30.67880821,  13.21205616,  18.70442963,  14.26610184,
          -53.19219589]],
 
        [[ -3.05774593,  -2.26609755,   3.43342209, 

In [7]:
# max pool

x = tf.constant([
     [
        [1,2,3],
        [11,12,13],
        [21,22,23],
        [41,42,43],
        [51,52,53],
        [61,62,63]
    ],
    [
        [71,72,73],
        [1,2,3],
        [81,82,83],
        [21,22,23],
        [91,92,93],
        [31,32,33],
    ]
])

print(x.shape)

ys1 = tf.layers.max_pooling1d(x, pool_size=2, strides=1, padding='same')

ys2 = tf.layers.max_pooling1d(x, pool_size=2, strides=2, padding='same')

yv1 = tf.layers.max_pooling1d(x, pool_size=2, strides=1, padding='valid')

yv2 = tf.layers.max_pooling1d(x, pool_size=2, strides=2, padding='valid')

print("ys1.shape = {}".format(ys1.shape))

print("ys2.shape = {}".format(ys2.shape))

print("yv1.shape = {}".format(yv1.shape))

print("yv2.shape = {}".format(yv2.shape))

ys1,  ys2, yv1, yv2 = sess.run([ys1,  ys2, yv1, yv2])

print(ys1)
print(ys2)
print(yv1)
print(yv2)

(2, 6, 3)
ys1.shape = (2, 6, 3)
ys2.shape = (2, 3, 3)
yv1.shape = (2, 5, 3)
yv2.shape = (2, 3, 3)
[[[11 12 13]
  [21 22 23]
  [41 42 43]
  [51 52 53]
  [61 62 63]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [81 82 83]
  [91 92 93]
  [91 92 93]
  [31 32 33]]]
[[[11 12 13]
  [41 42 43]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [91 92 93]]]
[[[11 12 13]
  [21 22 23]
  [41 42 43]
  [51 52 53]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [81 82 83]
  [91 92 93]
  [91 92 93]]]
[[[11 12 13]
  [41 42 43]
  [61 62 63]]

 [[71 72 73]
  [81 82 83]
  [91 92 93]]]


In [33]:
# residual connection with different shape
x = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9],
        [11,12,13,14,15,16,17,18,19]
    ],
    [
        [11,2,13,14,5,16,7,18,9],
        [1,12,3,4,15,6,17,8,19]
    ]
])

print(x.shape)

y = tf.constant([
     [
        [1,2,3,4,5,6,7,8,9]
    ],
    [
        [11,2,13,14,5,16,7,18,9]
    ]
])

print(y.shape)

sess.run(x + y)

(2, 2, 9)
(2, 1, 9)


array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
        [12, 14, 16, 18, 20, 22, 24, 26, 28]],

       [[22,  4, 26, 28, 10, 32, 14, 36, 18],
        [12, 14, 16, 18, 20, 22, 24, 26, 28]]], dtype=int32)