In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

In [4]:
# tf.zeros_like

t = tf.constant([0,1,2,3,4,5,6,7,8,9])

g = tf.zeros_like(t)

sess.run(g)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [16]:
# subscripting

t = tf.constant([
    [[1,2], [3,4], [5,6]],
    [[7,8], [9,10], [11,12]]
])

a = sess.run(t[:1,:,:])
b = sess.run(t[:,:1,:])
c = sess.run(t[:,:,:1])
d = sess.run(t[:,:-1,:])

print("a = {}".format(a))
print("b = {}".format(b))
print("c = {}".format(c))
print("d = {}".format(d))

t = tf.constant([0,1,2,3,4,5,6,7,8,9])

a = sess.run(t[:1])
b = sess.run(t[:-1])
a, b

a = [[[1 2]
  [3 4]
  [5 6]]]
b = [[[1 2]]

 [[7 8]]]
c = [[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]]
d = [[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [ 9 10]]]


(array([0], dtype=int32), array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32))